 
# checkout this  link https://github.com/davidcavazos/python-docs-samples/blob/master/dataflow/gpu-workers/cloudbuild.yaml

steps:
  # Build the container image with the Python version of our choice.
  - name: gcr.io/cloud-builders/docker
    args:
      [ 'build'
      , '--tag=gcr.io/$PROJECT_ID/$_IMAGE_NAME'
      , '--file=./dataflow/pipeline/Dockerfile_pipeline'
      , './dataflow/pipeline/'
      ]
    
      
images: ['gcr.io/$PROJECT_ID/$_IMAGE_NAME']


substitutions:
  _IMAGE_NAME: pipeline:latestRun
