 
# checkout this  link https://github.com/davidcavazos/python-docs-samples/blob/master/dataflow/gpu-workers/cloudbuild.yaml

steps:
  # Build the container image with the Python version of our choice.
  - name: gcr.io/cloud-builders/docker
    args:
      [ 'build'
      , '--tag=gcr.io/$PROJECT_ID/$_IMAGE_NAME'
      , '--file=./Dockerfile_pipeline'
      , '.'
      ]
  # Push docker image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'gcr.io/$_PROJECT_ID/$_IMAGE_NAME']
    id: 'push-image'

  # Build flex template
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: 
      [ 
          'dataflow'
          , 'flex-template'
          , 'build'
          , '$_TEMPLATE_GCS_LOCATION'
          , '--image'
          , 'gcr.io/$_PROJECT_ID/$_IMAGE_NAME'
          , '--sdk-language'
          , 'PYTHON'
          , '--metadata-file'
          , '$_METADATA_FILE']  
    id: 'build-flex-template'

substitutions:
  _PROJECT_ID: datascience-projects
  _IMAGE_NAME: pipeline:latestRun
  _TEMPLATE_GCS_LOCATION: gs://mm_dataflow_bucket/templates/pipeline_flex_template.json
  _METADATA_FILE: metadata.json 
  
  
