steps:
  # Build the container image with the Python version of our choice.
  - name: gcr.io/cloud-builders/docker
    args:
      [ 'build'
      , '--tag=gcr.io/$PROJECT_ID/$_IMAGE_NAME'
      , '--file=./Dockerfile_test'
      , '.'
      ]
    id: 'build-image'
  # Push docker image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'gcr.io/$_PROJECT_ID/$_IMAGE_NAME']
    id: 'push-image'
    waitFor: ['build-image']

substitutions:
  _PROJECT_ID: datascience-projects
  _IMAGE_NAME: tester:latestRun
  
