# This approach only seem to work with beam < 2.30.0
substitutions:
  _TEMP_LOCATION: ''
  _FMPKEY: '' 
  _TEMPLATE_GCS_LOCATION: gs://mm_dataflow_bucket/templates/pipeline_flex_template.json
  _JOB_NAME: 'pipelinerunner'
  _REGION: us-central1
  
steps:
  # Run Flex Template different way
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: 
      [ 
          'dataflow'
          , 'flex-template'
          , 'run'
          , '$_JOB_NAME'
          , '--template-file-gcs-location'
          , '$_TEMPLATE_GCS_LOCATION'
          , '--parameters'
          , 'year=2017'
          , '--parameters'
          , 'quarter=QTR1'
          , '--parameters'
          , 'fmpkey=$_FMPKEY'
          , '--region=$_REGION'
          ]  
    id: 'build-flex-template-via-cloudsdk'


