
# checkout this  link https://github.com/davidcavazos/python-docs-samples/blob/master/dataflow/gpu-workers/cloudbuild.yaml

steps:
  # Run Flex Template different way
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: 
      [ 
          'dataflow'
          , 'flex-template'
          , 'run'
          , '$_JOB_NAME'
          , '--template-file-gcs-location'
          , '$_TEMPLATE_GCS_LOCATION'
          , '--parameters'
          , 'year=2017'
          , '--parameters'
          , 'quarter=QTR1'
          , '--parameters'
          , 'fmpkey=$_FMPKEY'
          , '--region=$_REGION'
          ]  
    id: 'build-flex-template-via-cloudsdk'

substitutions:
  _TEMPLATE_GCS_LOCATION: gs://mm_dataflow_bucket/templates/pipeline_flex_template.json
  _JOB_NAME: 'pipelinerunner'
  _REGION: us-central1
  _FMPKEY: ''  

