
# Building all the images every time we commit here
# checkout this  link https://github.com/davidcavazos/python-docs-samples/blob/master/dataflow/gpu-workers/cloudbuild.yaml
# Note:this file will be invoked by a cloud trigger, that's why we need to specify as third argument of the build command
# the relative path of the directory
# to be amended. this should invoke build file for each subproject
steps:
  # Build the container image with the Python version of our choice.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: 
      [ 
          'builds'
          , 'submit'
          , '--verbosity'
          , 'debug'
          , '--config'
          , '$_EDGAR_FORM4_BUILD_FILE']  
    id: 'build-edgarform4-templates'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: 
      [ 
          'builds'
          , 'submit'
          , '--verbosity'
          , 'debug'
          , '--config'
          , '$_EDGAR_FORM13_BUILD_FILE']  
    id: 'build-edgarform13-templates'
  
  - name: gcr.io/cloud-builders/docker
    args:
      [ 'build'
      , '--tag=gcr.io/$_PROJECT_ID/$_EDGAR_QUARTERLY_FORM4_IMAGE_NAME'
      , '--file=./dataflow/edgar_flow/Dockerfile_Edgar_Quarterly_Form4'
      , './dataflow/edgar_flow/'
      ]
    id: 'build-quarterly_form4-image'
  # Kick off pipeline build
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: 
      [ 
          'builds'
          , 'submit'
          , '--verbosity'
          , 'debug'
          , '--config'
          , '$_PIPELINE_BUILD_FILE']  
    id: 'build-pipeline-template'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: 
      [ 
          'builds'
          , 'submit'
          , '--verbosity'
          , 'debug'
          , '--config'
          , '$_SHARELOADER_BUILD_FILE']  
    id: 'build-shareloader-templates'
  
timeout: 82000s

images: ['gcr.io/$_PROJECT_ID/$_EDGAR_QUARTERLY_FORM4_IMAGE_NAME',
          ]

   

substitutions:
  _PROJECT_ID: datascience-projects
  _PIPELINE_BUILD_FILE: ./dataflow/pipeline/build.yaml
  _EDGAR_DAILY_FORM13_IMAGE_NAME: edgar-daily-form13:latest
  _EDGAR_QUARTERLY_FORM4_IMAGE_NAME: edgar-quarterly-form4:latest
  _SHARELOADER_BUILD_FILE: ./dataflow/shareloader/build_all.yaml
  _EDGAR_FORM4_BUILD_FILE: ./dataflow/edgar_flow/cloudbuild_edgar_daily_form4.yaml
  _EDGAR_FORM13_BUILD_FILE: ./dataflow/edgar_flow/cloudbuild_edgar_daily_form13.yaml
  _STOCKSELECTION_BUILD_FILE: ./dataflow/shareloader/build_weeklyselection.yaml

  
