 
# checkout this  link https://github.com/davidcavazos/python-docs-samples/blob/master/dataflow/gpu-workers/cloudbuild.yaml

steps:
  # Build the container image with the Python version of our choice.
  - name: gcr.io/cloud-builders/docker
    args:
      [ 'build'
      , '--tag=gcr.io/$_PROJECT_ID/$_IMAGE_NAME'
      , '--file=./dataflow/shareloader/Dockerfile_shareloader'
      , './dataflow/shareloader/'
      ]
    id: 'build-shareloader-image'
  # Build flex template
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: 
      [ 
          'dataflow'
          , 'flex-template'
          , 'build'
          , '$_SHARELOADER_TEMPLATE_GCS_LOCATION'
          , '--image'
          , 'gcr.io/$_PROJECT_ID/$_IMAGE_NAME'
          , '--staging-location=gs://datascience-projects_cloudbuild/staging'
          , '--sdk-language'
          , 'PYTHON'
          , '--metadata-file'
          , '$_SHARELOADER_METADATA_FILE'
      ]
    id: 'build-shareloader-flex-template'


images: ['gcr.io/$_PROJECT_ID/$_IMAGE_NAME']

timeout: 7200s
substitutions:
  _PROJECT_ID: datascience-projects
  _IMAGE_NAME: shareloader:latest2
  _SHARELOADER_TEMPLATE_GCS_LOCATION: gs://mm_dataflow_bucket/templates/shareloader_flex_template.json
  _SHARELOADER_METADATA_FILE: ./dataflow/shareloader/shares_pipeline_template_metadata 

