 
# checkout this  link https://github.com/davidcavazos/python-docs-samples/blob/master/dataflow/gpu-workers/cloudbuild.yaml

steps:
  # Build the container image with the Python version of our choice.
  - name: gcr.io/cloud-builders/docker
    args:
      [ 'build'
      , '--tag=gcr.io/$_PROJECT_ID/$_MARKETSTATS_IMAGE_NAME'
      , '--file=./dataflow/shareloader/Dockerfile_marketstats'
      , './dataflow/shareloader/'
      ]
    id: 'build-marketstats-image'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: 
      [ 
          'dataflow'
          , 'flex-template'
          , 'build'
          , '$_MARKETSTATS_TEMPLATE_GCS_LOCATION'
          , '--image'
          , 'gcr.io/$_PROJECT_ID/$_MARKETSTATS_IMAGE_NAME'
          , '--sdk-language'
          , 'PYTHON'
          , '--metadata-file'
          , '$_MARKETSTATS_METADATA_FILE']  
    id: 'build-marketstats-flex-template'


images: [ 'gcr.io/$_PROJECT_ID/$_MARKETSTATS_IMAGE_NAME' ]


substitutions:
  _PROJECT_ID: datascience-projects
  _MARKETSTATS_IMAGE_NAME: marketstats:latest
  _MARKETSTATS_TEMPLATE_GCS_LOCATION: gs://mm_dataflow_bucket/templates/marketstats_flex_template.json
  _MARKETSTATS_METADATA_FILE: ./dataflow/shareloader/marketstats_template_metadata

