 
# checkout this  link https://github.com/davidcavazos/python-docs-samples/blob/master/dataflow/gpu-workers/cloudbuild.yaml

steps:
  # Build the container image with the Python version of our choice.
  - name: gcr.io/cloud-builders/docker
    args:
      [ 'build'
      , '--tag=gcr.io/$_PROJECT_ID/$_ECONOMY_IMAGE_NAME'
      , '--file=./dataflow/shareloader/Dockerfile_stateofeconomy'
      , './dataflow/shareloader/'
      ]
    id: 'build-stateofeconomy-image'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: 
      [ 
          'dataflow'
          , 'flex-template'
          , 'build'
          , '$_ECONOMY_TEMPLATE_GCS_LOCATION'
          , '--image'
          , 'gcr.io/$_PROJECT_ID/$_ECONOMY_IMAGE_NAME'
          , '--sdk-language'
          , 'PYTHON'
          , '--metadata-file'
          , '$_ECONOMY_METADATA_FILE']
    id: 'build-economy-flex-template'


images: [ 'gcr.io/$_PROJECT_ID/$_ECONOMY_IMAGE_NAME' ]


substitutions:
  _PROJECT_ID: datascience-projects
  _ECONOMY_IMAGE_NAME: stateofeconomy:latest
  _ECONOMY_TEMPLATE_GCS_LOCATION: gs://mm_dataflow_bucket/templates/state_of_economy_flex_template.json
  _ECONOMY_METADATA_FILE: ./dataflow/shareloader/state_of_economy_template_metadata

