 
# checkout this  link https://github.com/davidcavazos/python-docs-samples/blob/master/dataflow/gpu-workers/cloudbuild.yaml

steps:
  # Build the container image with the Python version of our choice.
  - name: gcr.io/cloud-builders/docker
    args:
      [ 'build'
      , '--tag=gcr.io/$_PROJECT_ID/$_IMAGE_NAME'
      , '--file=./dataflow/shareloader/Dockerfile_shareloader'
      , './dataflow/shareloader/'
      ]
    id: 'build-shareloader-image'
  # Build flex template
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: 
      [ 
          'dataflow'
          , 'flex-template'
          , 'build'
          , '$_SHARELOADER_TEMPLATE_GCS_LOCATION'
          , '--image'
          , 'gcr.io/$_PROJECT_ID/$_IMAGE_NAME'
          , '--sdk-language'
          , 'PYTHON'
          , '--metadata-file'
          , '$_SHARELOADER_METADATA_FILE']  
    id: 'build-shareloader-flex-template'
  - name: gcr.io/cloud-builders/docker
    args:
      [ 'build'
      , '--tag=gcr.io/$_PROJECT_ID/$_MARKETSTATS_IMAGE_NAME'
      , '--file=./dataflow/shareloader/Dockerfile_marketstats'
      , './dataflow/shareloader/'
      ]
    id: 'build-marketstats-image'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: 
      [ 
          'dataflow'
          , 'flex-template'
          , 'build'
          , '$_MARKETSTATS_TEMPLATE_GCS_LOCATION'
          , '--image'
          , 'gcr.io/$_PROJECT_ID/$_MARKETSTATS_IMAGE_NAME'
          , '--sdk-language'
          , 'PYTHON'
          , '--metadata-file'
          , '$_MARKETSTATS_METADATA_FILE']  
    id: 'build-marketstats-flex-template'
  - name: gcr.io/cloud-builders/docker
    id: 'dftester-image'
    args:
      [ 'build'
      , '--tag=gcr.io/$_PROJECT_ID/$_DFTESTER_IMAGE_NAME'
      , '--file=./dataflow/shareloader/Dockerfile_tester'
      , './dataflow/shareloader/'
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'build-dftester-flex-template'
    entrypoint: 'gcloud'
    args:
      [
          'dataflow'
        , 'flex-template'
        , 'build'
        , '$_DFTESTER_TEMPLATE_GCS_LOCATION'
        , '--image'
        , 'gcr.io/$_PROJECT_ID/$_DFTESTER_IMAGE_NAME'
        , '--sdk-language'
        , 'PYTHON'
        , '--metadata-file'
        , '$_DFTESTER_METADATA_FILE' ]



images: ['gcr.io/$_PROJECT_ID/$_IMAGE_NAME', 'gcr.io/$_PROJECT_ID/$_MARKETSTATS_IMAGE_NAME', 'gcr.io/$_PROJECT_ID/$__DFTESTER_IMAGE_NAME' ]


substitutions:
  _PROJECT_ID: datascience-projects
  _IMAGE_NAME: shareloader:latest2
  _SHARELOADER_TEMPLATE_GCS_LOCATION: gs://mm_dataflow_bucket/templates/shareloader_flex_template.json
  _SHARELOADER_METADATA_FILE: ./dataflow/shareloader/shares_pipeline_template_metadata 
  _MARKETSTATS_IMAGE_NAME: marketstats:latest
  _MARKETSTATS_TEMPLATE_GCS_LOCATION: gs://mm_dataflow_bucket/templates/marketstats_flex_template.json
  _MARKETSTATS_METADATA_FILE: ./dataflow/shareloader/marketstats_template_metadata
  _DFTESTER_IMAGE_NAME: dftester:latest
  _DFTESTER_TEMPLATE_GCS_LOCATION: gs://mm_dataflow_bucket/templates/dftester_flex_template.json
  _DFTESTER_METADATA_FILE: ./dataflow/shareloader/dftester_template_metadata

