
# checkout this  link https://github.com/davidcavazos/python-docs-samples/blob/master/dataflow/gpu-workers/cloudbuild.yaml

steps:
  # Build the container image with the Python version of our choice.
  - name: gcr.io/cloud-builders/docker
    id: 'dftester-image'
    args:
      [   'build'
        , '--tag=gcr.io/$_PROJECT_ID/$_MKTSTATS2_IMAGE_NAME'
        , '--file=./dataflow/shareloader/Dockerfile_marketstats2'
        , './dataflow/shareloader/'
      ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'build-dftester-flex-template'
    entrypoint: 'gcloud'
    args:
      [
          'dataflow'
        , 'flex-template'
        , 'build'
        , '$_MKTSTATS2_TEMPLATE_GCS_LOCATION'
        , '--image'
        , 'gcr.io/$_PROJECT_ID/$_MKTSTATS2_IMAGE_NAME'
        , '--sdk-language'
        , 'PYTHON'
        , '--staging-location=gs://datascience-projects_cloudbuild/staging'
        , '--metadata-file'
        , '$_MKTSTATS2_METADATA_FILE' ]


images: [ 'gcr.io/$_PROJECT_ID/$_MKTSTATS2_IMAGE_NAME' ]

substitutions:
  _PROJECT_ID: datascience-projects
  _MKTSTATS2_IMAGE_NAME: mkstats2:latest_33
  _MKTSTATS2_TEMPLATE_GCS_LOCATION: gs://mm_dataflow_bucket/templates/mktstats2_flex_template_33.json
  _MKTSTATS2_METADATA_FILE: ./dataflow/shareloader/marketstats_template_metadata

