
# Building all the images every time we commit here
# checkout this  link https://github.com/davidcavazos/python-docs-samples/blob/master/dataflow/gpu-workers/cloudbuild.yaml
# Note:this file will be invoked by a cloud trigger, that's why we need to specify as third argument of the build command
# the relative path of the directory
# to be amended. this should invoke build file for each subproject
steps:
  # Build the container image with the Python version of our choice.
  # Kick off shareloader
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: 
      [ 
          'builds'
          , 'submit'
          , '--verbosity'
          , 'debug'
          , '--config'
          , '$_SHARELOADER_BUILD_FILE']  
    id: 'build-shareloader-template'
  # Kick off shares dataset
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: 
      [ 
          'builds'
          , 'submit'
          , '--verbosity'
          , 'debug'
          , '--config'
          , '$_SHARESDATASETLOADER_BUILD_FILE']  
    id: 'build-datasetloader-template'
  # Kick off superperformers
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: 
      [ 
          'builds'
          , 'submit'
          , '--verbosity'
          , 'debug'
          , '--config'
          , '$_SUPERPERFORMERS_BUILD_FILE']  
    id: 'build-superperformers-template'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: 
      [ 
          'builds'
          , 'submit'
          , '--verbosity'
          , 'debug'
          , '--config'
          , '$_ECONOMY_BUILD_FILE']  
    id: 'build-stateofeconomy-template'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
          'builds'
        , 'submit'
        , '--verbosity'
        , 'debug'
        , '--config'
        , '$_ECONOMY_EMAIL_BUILD_FILE' ]
    id: 'build-economy_email-template'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
          'builds'
        , 'submit'
        , '--verbosity'
        , 'debug'
        , '--config'
        , '$_PREMARKETLOADER_BUILD_FILE' ]
    id: 'build-premarketloader-template'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: 'gcloud'
      args:
        [
            'builds'
          , 'submit'
          , '--verbosity'
          , 'debug'
          , '--config'
          , '$_WEEKLYSELECTION_BUILD_FILE' ]
      id: 'build-weeklyselection-template'
timeout: 50000s
substitutions:
  _SHARELOADER_BUILD_FILE: ./dataflow/shareloader/build_shareloader.yaml
  _SHARESDATASETLOADER_BUILD_FILE: ./dataflow/shareloader/shares_datset_build.yaml
  _SUPERPERFORMERS_BUILD_FILE: ./dataflow/shareloader/superperformers_build.yaml
  _ECONOMY_BUILD_FILE: ./dataflow/shareloader/build_stateofeconomy.yaml
  _ECONOMY_EMAIL_BUILD_FILE: ./dataflow/shareloader/build_economics_email.yaml
  _PREMARKETLOADER_BUILD_FILE: ./dataflow/shareloader/premarketloader_build.yaml
  _WEEKLYSELECTION_BUILD_FILE: ./dataflow/shareloader/build_weeklyselection.yaml
  
