 
# checkout this  link https://github.com/davidcavazos/python-docs-samples/blob/master/dataflow/gpu-workers/cloudbuild.yaml

steps:
  # Build the container image with the Python version of our choice.
  - name: gcr.io/cloud-builders/docker
    args:
      [ 'build'
      , '--tag=gcr.io/$_PROJECT_ID/$_IMAGE_NAME'
      , '--file=./Dockerfile_shareloader'
      , '.'
      ]
    id: 'build-shareloader-image'
  - name: gcr.io/cloud-builders/docker
    args:
      [ 'build'
      , '--tag=gcr.io/$_PROJECT_ID/$_MARKETSTATS_IMAGE_NAME'
      , '--file=./Dockerfile_marketstats'
      , '.'
      ]
    id: 'build-marketstats-image'



images: ['gcr.io/$_PROJECT_ID/$_IMAGE_NAME', 'gcr.io/$_PROJECT_ID/$_MARKETSTATS_IMAGE_NAME' ]


substitutions:
  _IMAGE_NAME: shareloader:latest2
  _PROJECT_ID: datascience-projects
  _MARKETSTATS_IMAGE_NAME: marketstats:latest
