steps:
  # Run Flex Template different way
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: 
      [ 
          'dataflow'
          , 'flex-template'
          , 'run'
          , '$_JOB_NAME'
          , '--template-file-gcs-location'
          , '$_TEMPLATE_GCS_LOCATION'
          , '--parameters'
          , 'recipients=mmistroni@gmail.com'
          , '--parameters'
          , 'key=$_SENDGRIDKEY'
          , '--parameters'
          , 'iexkey=$_IEXKEY'
          , '--parameters'
          , 'sector=Utilities'
          , '--region=$_REGION'
          ]  
    id: 'build-flex-template-via-cloudsdk'



substitutions:
  _TEMPLATE_GCS_LOCATION: gs://mm_dataflow_bucket/templates/newsloader_flex_template.json
  _JOB_NAME: cloudbuildnewsrun
  _REGION : 'us-central1'
  _IEXKEY : ''
  _SENDGRIDKEY: ''