steps:
  # Run Flex Template different way
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: 
      [ 
          'dataflow'
          , 'flex-template'
          , 'run'
          , '$_JOB_NAME'
          , '--template-file-gcs-location'
          , '$_TEMPLATE_GCS_LOCATION'
          , '--parameters'
          , 'fmprepkey=$_FMPKEY'
          , '--parameters'
          , 'mmrun=$_MMRUN'
          , '--parameters'
          , 'numdays=$_NUMDAYS'
          , '--parameters'
          , 'sendgridkey=$_SENDGRIDKEY'
          , '--parameters'
          , 'inputfile=$_INPUTFILE'

        ,'--region=$_REGION'
          ]  
    id: 'build-flex-template-via-cloudsdk'

substitutions:
  _TEMPLATE_GCS_LOCATION: gs://mm_dataflow_bucket/templates/premarketloader_flex_template.json
  _JOB_NAME: cloudbuildpremarketloader
  _REGION : 'us-central1'
  _FMPKEY : ''
  _MMRUN : ''
  _INPUTFILE: ''
  _NUMDAYS: '10'
  _SENDGRIDKEY : ''
