steps:
  # Run Flex Template different way
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: 
      [ 
          'dataflow'
          , 'flex-template'
          , 'run'
          , '$_JOB_NAME'
          , '--template-file-gcs-location'
          , '$_TEMPLATE_GCS_LOCATION'
          , '--parameters'
          , 'key=$_SENDGRID_KEY'
          , '--parameters'
          , 'fmprepkey=$_FMPREP_KEY'
          , '--region=$_REGION'
          , '--staging-location=gs://datascience-projects_cloudbuild'
          ]  
    id: 'build-flex-template-via-cloudsdk'



substitutions:
  _TEMPLATE_GCS_LOCATION: gs://mm_dataflow_bucket/templates/shareloader_flex_template.json
  _JOB_NAME: 'shareloadercloudbuild2'
  _REGION : 'us-central1'
  _FMPREP_KEY : ''
  _SENDGRID_KEY: ''

#options:
#  logging: CLOUD_LOGGING_ONLY

# Use the Compute Engine default service account to launch the job.
#serviceAccount: projects/$PROJECT_ID/serviceAccounts/$PROJECT_NUMBER-compute@developer.gserviceaccount.com
