steps:
# Run Flex Template different way
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: 
      [ 
          'dataflow'
          , 'flex-template'
          , 'run'
          , '$_JOB_NAME'
          , '--template-file-gcs-location'
          , '$_WEEKLYSELECTION_TEMPLATE_GCS_LOCATION'
          , '--parameters'
          , 'sendgridkey=$_SENDGRID_KEY'
          , '--parameters'
          , 'recipients=$_RECIPIENTS'
          , '--region=$_REGION'

      ]
    id: 'build-flex-template-via-cloudsdk'

substitutions:
  _JOB_NAME: 'weeklyselectioncloudbuild'
  _WEEKLYSELECTION_TEMPLATE_GCS_LOCATION: gs://mm_dataflow_bucket/templates/marketstats_flex_template.json
  _REGION: us-central1
  _SENDGRID_KEY : ''
  _RECIPIENTS : ''

