steps:
# Run Flex Template different way
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    id: 'build-dftester-template-via-cloudsdk'
    args:
      [
          'dataflow'
          , 'flex-template'
          , 'run'
          , '$_JOB_NAME'
          , '--template-file-gcs-location'
          , '$_MKTSTATS2_TEMPLATE_GCS_LOCATION'
          , '--parameters'
          , 'key=$_FMPREP_KEY'
          , '--parameters'
          , 'sendgridkey=$_SENDGRID_KEY'
          , '--parameters'
          , 'recipients=$_RECIPIENTS'
          , '--parameters'
          , 'fredkey=$_FREDKEY'
          , '--parameters'
          , 'sdk_container_image=$_SDK_CONTAINER_IMAGE'
          ,'--region=$_REGION'
          ,'--subnetwork=regions/us-central1/subnetworks/default'
          , '--staging-location=gs://datascience-projects_cloudbuild'
          ]
substitutions:
  _JOB_NAME: 'marketstats2'
  _MKTSTATS2_TEMPLATE_GCS_LOCATION: gs://mm_dataflow_bucket/templates/mktstats2_flex_template_33.json
  _REGION: us-central1
  _FMPREP_KEY: ''
  _SENDGRID_KEY: ''
  _RECIPIENTS: 'mmistroni@gmail.com'
  _FRED_KEY: ''
  _PROJECT_ID: datascience-projects
  _SDK_CONTAINER_IMAGE: gcr.io/datascience-projects/mkstats2:latest_33



