steps:
# Run Flex Template different way
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    id: 'build-dftester-template-via-cloudsdk'
    args: 
      [ 
          'dataflow'
          , 'flex-template'
          , 'run'
          , '$_JOB_NAME'
          , '--template-file-gcs-location'
          , '$_DFTESTER_TEMPLATE_GCS_LOCATION'
          , '--parameters'
          , 'fmprepkey=$_FMPREP_KEY'
          '--region=$_REGION'
          ]  
substitutions:
  _JOB_NAME: 'dftester'
  _DFTESTER_TEMPLATE_GCS_LOCATION: gs://mm_dataflow_bucket/templates/dftester_flex_template.json
  _REGION: us-central1
  _FMPREP_KEY: ''


