steps:
# Run Flex Template different way
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    id: 'build-dftester-template-via-cloudsdk'
    args: 
      [ 
          'dataflow'
          , 'flex-template'
          , 'run'
          , '$_JOB_NAME'
          , '--template-file-gcs-location'
          , '$_DFTESTER_TEMPLATE_GCS_LOCATION'
          , '--parameters'
          , 'fmprepkey=$_FMPREP_KEY'
          , '--parameters'
          , 'input=$_INPUT'
          , '--parameters'
          , 'output=$_OUTPUT'
          , '--parameters'
          , 'period=$_PERIOD'
          , '--parameters'
          ,'limit=$_LIMIT'
          , '--parameters'
          ,'runtype=$_RUNTYPE'
          , '--parameters'
          ,'sendgridkey=$_SENDGRIDKEY'
          , '--parameters'
          ,'openaikey=$_OPENAIKEY'
          , '--parameters'
          ,'googleapikey=$_GOOGLEAPIKEY'
          , '--parameters'
          ,'agent_url=$_AGENT_URL'
        , '--parameters'
          , 'sdk_container_image=$_SDK_CONTAINER_IMAGE'
          ,'--region=$_REGION'
          ,'--subnetwork=regions/us-central1/subnetworks/default'
          , '--staging-location=gs://datascience-projects_cloudbuild'
          ]  
substitutions:
  _DFTESTER_TEMPLATE_GCS_LOCATION: gs://mm_dataflow_bucket/templates/dftester_flex_template.json
  _REGION: us-central1
  _FMPREP_KEY: ''
  _INPUT: ''
  _OUTPUT: ''
  _PERIOD: 'annual'
  _LIMIT: '10'
  _SENDGRIDKEY: ''
  _OPENAIKEY: ''
  _GOOGLEAPIKEY: ''
  _AGENT_URL: ''
  _RUNTYPE: ''
  _JOB_NAME: 'dftester'
  _PROJECT_ID: datascience-projects
  _SDK_CONTAINER_IMAGE: gcr.io/datascience-projects/dftester:latest47



