steps:
# Run Flex Template different way
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: 
      [ 
          'dataflow'
          , 'flex-template'
          , 'run'
          , '$_JOB_NAME'
          , '--template-file-gcs-location'
          , '$_MARKETSTATS_TEMPLATE_GCS_LOCATION'
          , '--parameters'
          , 'key=$_FMPREP_KEY'
          , '--parameters'
          , 'sendgridkey=$_SENDGRID_KEY'
          , '--region=$_REGION'
          ]  
    id: 'build-flex-template-via-cloudsdk'

substitutions:
  _JOB_NAME: 'marketstatscloudbuild'
  _MARKETSTATS_TEMPLATE_GCS_LOCATION: gs://mm_dataflow_bucket/templates/marketstats_flex_template.json
  _REGION: us-central1
  _FMPREP_KEY: ''
  _SENDGRID_KEY : ''

