steps:
  # Build the container image with the Python version of our choice.
  - name: gcr.io/cloud-builders/docker
    args:
      [ 'build'
      , '--tag=gcr.io/$_PROJECT_ID/$_IMAGE_NAME'
      , '--file=./dataflow/edgar_flow/Dockerfile_Edgar_Daily_Form13'
      , './dataflow/edgar_flow'
      ]
    id : 'build-edgarform13-image'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: 
      [ 
          'dataflow'
          , 'flex-template'
          , 'build'
          , '$_TEMPLATE_GCS_LOCATION'
          , '--image'
          , 'gcr.io/$_PROJECT_ID/$_IMAGE_NAME'
          , '--sdk-language'
          , 'PYTHON'
          , '--metadata-file'
          , '$_EDGARFORM13_METADATA_FILE']  
    id: 'build-edgarform13-flex-template'
    waitFor: ['build-edgarform13-image']
  
images: ['gcr.io/$_PROJECT_ID/$_IMAGE_NAME']
timeout: 1800s

substitutions:
  _PROJECT_ID: datascience-projects
  _IMAGE_NAME: edgar-daily-form13:latest
  _TEMPLATE_GCS_LOCATION: gs://mm_dataflow_bucket/templates/python_command_spec_edgar_daily_form13.json
  _EDGARFORM13_METADATA_FILE : ./dataflow/edgar_flow/spec/edgar_dataflow_daily_template_metadata
