
# chec1kout this  link https://github.com/davidcavazos/python-docs-samples/blob/master/dataflow/gpu-workers/cloudbuild.yaml

steps:
  # Build the container image with the Python version of our choice.
  - name: gcr.io/cloud-builders/docker
    id : 'build-edgarform4-image'
    args:
      [ 'build'
      , '--tag=gcr.io/$_PROJECT_ID/$_IMAGE_NAME'
      , '--file=./dataflow/edgar_flow/Dockerfile'
      , './dataflow/edgar_flow'
      ]
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: 'build-edgarform4-flex-template'
    entrypoint: 'gcloud'
    args: 
      [ 
          'dataflow'
          , 'flex-template'
          , 'build'
          , '$_TEMPLATE_GCS_LOCATION'
          , '--image'
          , 'gcr.io/$_PROJECT_ID/$_IMAGE_NAME'
          , '--sdk-language'
          , 'PYTHON'
          , '--metadata-file'
          , '$_EDGARFORM4_METADATA_FILE'
          , '--staging-location=gs://datascience-projects_cloudbuild/staging'
      ]

images: [ 'gcr.io/$_PROJECT_ID/$_IMAGE_NAME' ]
timeout: 3600s
substitutions:
  _PROJECT_ID: datascience-projects
  _IMAGE_NAME: edgar-daily4-form4-cbuild:latest2
  _TEMPLATE_GCS_LOCATION: gs://mm_dataflow_bucket/templates/python_command_spec_edgar_daily_form4-cbuild.json
  _EDGARFORM4_METADATA_FILE : ./dataflow/edgar_flow/spec/edgar_dataflow_daily_form4_template_metadata
