steps:
  # Build the container image with the Python version of our choice.
  - name: gcr.io/cloud-builders/docker
    args:
      [ 'build'
      , '--tag=$_IMAGE_NAME'
      , '--file=./dataflow/edgar_flow/Dockerfile_Edgar_Daily_Form13'
      , './dataflow/edgar_flow'
      ]
images: ['$_IMAGE_NAME']


substitutions:
  _IMAGE_NAME: gcr.io/datascience-projects/edgar-daily-form13:latest
