steps:
  # Build the container image with the Python version of our choice.
  # Kick off edgar form4
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
          'builds'
          , 'submit'
          , '--verbosity'
          , 'debug'
          , '--config'
          , '$_EDGAR_FORM4_BUILD_FILE']
    id: 'build-form4-template'
  timeout: 50000s
substitutions:
  _EDGAR_FORM4_BUILD_FILE: ./dataflow/edgar_flow/cloudbuild_edgar_daily_form4.yaml
  _EDGAR_FORM13_BUILD_FILE: ./dataflow/edgar_flow/cloudbuild_edgar_daily_form13.yaml

